### ISSUE TITLE
generate openapi.yml instead of serving openapi

### ISSUE THREAD

**Issue by stefanomiccoli** [giddyinc/doctopus#22]
docs appear to be down, so apologies in advance if i miss something from there.

I really like the idea of annotations instead of bulky @swagger comments (huge mess identing properly) from `swagger-jsdoc`.

However in our current setup, we are not serving openapi from nodejs, but as part of our static docs site with redoc. For this reason we had previously set up a ci job that is triggered at code changes, generate yml file and then export it to our privately hosted docs (gitlab pages).

I couldnt find a quick way to achieve the same without coding my own script, I'm I right? Any suggestion?

Furthermore, our current scenario entails a monorepo with different services (some exposing rest endpoints) and api-contracts packages. With `swagger-jsdoc` we have `/** @swagger */` comments on each package which expose apis or define models. Then running it from the root of yarn workspace it basically parses any ts file from any package matching the glob rule. It there a way to achieve something like this with this cool project?

**Comment by blugavere** [comment]
>I couldnt find a quick way to achieve the same without coding my own script, I'm I right? Any suggestion?

as you pointed out, a script is the way to leverage this lib to generate docs in part of a ci/cd process and just upload it to a bucket once it's built. Here's a loose example - can add one to the repo if needed.

```ts
import fs from 'fs';
import path from 'path';
import {
  Doc,
  DocBuilder,
} from 'doctopus'

const docs = new DocBuilder();

// docs.use(SomeControllerClass)

docs.addDefinitions({ User }); // manually constructed using the lib or generated from something like  `mongoose-to-swagger`

docs.add('/users')
  .get()
  .group('User')
  .summary('Get Users')
  .description('Gets a set of Users')
  .build();

const result = docs
  .set('title', `My API Docs`)
  .build();

// write to the filesystem - could just upload to a cloud storage / s3 bucket instead
fs.writeFileSync(path.join(__dirname, './public/swagger.json'), JSON.stringify(result, null, 2), { encoding: 'utf8' });

```

note as seen here the 'decorator api' just requires you to import/register the class.

https://github.com/giddyinc/doctopus/blob/master/examples/typescript/src/app.ts#L25

> our current scenario entails a monorepo with different services

the lib was built around swagger 2.0 which only supports a single host. You'd be generating independent docs per service, but, you could script something that leverages the existing API contract packages by parsing your `swagger-jsdoc` annotations and loading them into a `doctopus` script outputting the final product somewhere using shared models.

```ts
docs.addDefinitions({ 
// your existing schema definitions here
});
```

> Then running it from the root of yarn workspace

I'm not super familiar with yarn but I think within your ci/cd process you'd just instrument each workspace to execute its own script to delegate the doc generation (i.e all execute doc.js in the cwd). you could also centralize this by coming up with conventions & just centralize the script @ the root.

```
// yarn <- can ju
services/
  serviceA/
    docs.js <- each yarn workspace could executes this
  serviceB/
    docs.js
```

https://classic.yarnpkg.com/en/docs/cli/workspaces#toc-yarn-workspaces-run


> parses any ts file from any package matching the glob rule

parsing from a regex is difficult to do because we're generating docs in code - so any db connections or i/o in general in the modules will actually run as part of the doc gen; you're effectively bootstrapping the application which has its own dependency graph. I'd recommend you set up a startup script which basically imports the modules, bootstraps the docs, outputs the file, and then shuts down. Can also just output based on env variable on startup, only used in CI/CD, etc.
